### PR TITLE
code for outputting to krux

### PR DESCRIPTION
**Pull request by kiyoto**
This is for the upcoming "Output to Krux" feature. Currently, Krux requires that all data import into Krux to be batched up into a single file. This workflow takes care of that.

### CODE REVIEW

**Comment by kiyoto** [comment]
@toru-takahashi This is to be used alongside https://support.treasuredata.com/hc/en-us/articles/360022986353-Salesforce-DMP-Krux-Export-BETA-

**Comment by toru-takahashi** [comment]
Any readme to run it?

**Comment by kiyoto** [comment]
@toru-takahashi added readme.

**Comment by toru-takahashi** [comment]
Thank you! Merged.

**Pull request merged**
