### PR TITLE
Refine min-max normalization and missing value interpolation scheme

### PR DESCRIPTION
**Pull request by takuti**
In the ML workflows, min/max values for evaluation should be computed on all observed data including train samples.

Meanwhile, missing values (NULLs) in test data are currently filled by avg. of test samples, but interpolating avg. of train data is more reasonable because the distribution of test samples is likely to be imbalanced.

### CODE REVIEW

**Comment by myui** [comment]
BTW, digdag task, where split time range is not provided, would be something as follows:

```
+preprocess:
  +min_max:
  +prepare_feature_vector:

+eval_and_main:

  +evaluate:
    
    +prepare_train_test:
     _parallel: true
  
      # 7:3 split
      +prepare_train:  
      +prepare_test:
  
    +traing:
    
    +predict_and_evaluate:
  
  +main:
  
    +train:
    # training using 100% dataset 
  
    +predict:

    +optional_quantile_computation:
```

**Comment by takuti** [comment]
@myui Thanks.

> Missing values of testing data should be filled in the same manner to one for training data.

Do you mean 100248bb34bbfa1aed14f133621919f56a2da719 this change is unnecessary?

**Comment by myui** [comment]
https://github.com/treasure-data/workflow-examples/commit/100248bb34bbfa1aed14f133621919f56a2da719 is a valid approach. Previous one is wrong.

**Comment by takuti** [comment]
Ah okay, so everything looks good to you.

**Pull request merged**
