### PR TITLE
Ivan/intermediate table

### PR DESCRIPTION
**Pull request by hadrianhu**
Hi @toru-takahashi. I've added some more details to the docs for intermediate table as we had discussed. Please let me know if I missed anything or if I need to change anything.

### CODE REVIEW

**Comment by hadrianhu** [comment]
Got it, thank you. I'll and a section explaining why.

**Comment by toru-takahashi** [comment]
Thanks.
Having a link to this article would be good: https://blog.treasuredata.com/blog/2017/07/25/analyze-infinitely-growing-data-incremental-queries/
Or, adding a knowledge in this article to this example would be nice.

**Comment by hadrianhu** [comment]
ok great, I'll incorporate that article as well. thank you

**Comment by toru-takahashi** [comment]
Great! Thank you!

**Pull request closed without merging**
