### PR TITLE
Add td-result-output-s3 example

### PR DESCRIPTION
**Pull request by ksukenoda**

### CODE REVIEW

**Comment by toru-takahashi** [comment]
Please use "secrets" for S3 credentials
That's why we need an example.

```
td wf secrets --project xxx --set s3.accesskey=yyy
or
td wf secrets --local --set s3.accesskey=yyy
```

Then, you can use `s3://${secret:s3.accesskey}:...`

Also, could you add a list of result_url parameter for s3?

compression and ...

**Comment by ksukenoda** [comment]
Updated. Please check it out. @toru-takahashi

**Comment by toru-takahashi** [comment]
Overall looks good.
One point, `td wf start td_load_example daily_load` sounds strange.
Because this example is to export data. So, daily_export would be better.

**Comment by ksukenoda** [comment]
Oops, modified to sample.

**Comment by toru-takahashi** [comment]
Ah, the follwoing doesn't work.
Because dig filename is td_s3.dig.
So, `td wf start sample_project td_s3` is correct.

`td wf start sample_project sample --session now`

**Comment by ksukenoda** [comment]
Modified.

**Comment by toru-takahashi** [comment]
Looks good to me. Merged.

**Pull request merged**
