### PR TITLE
add td result output to Microsoft azure blob storage example

### PR DESCRIPTION
**Pull request by ksukenoda**
Please check it out.

### CODE REVIEW

**Comment by toru-takahashi** [comment]
Readme says, "This example workflow ingests data in daily basis,".
But, the workflow is just for adhoc usecase.

**Comment by ksukenoda** [comment]
Thanks for pointing it. Modified.

**Comment by toru-takahashi** [comment]
Could you add parameters to _export like Kammy's one?
https://github.com/treasure-data/workflow-examples/blob/master/td/ftp/td_ftp.dig

**Comment by ksukenoda** [comment]
Changed. Please let me know if any other!

**Comment by ksukenoda** [comment]
Thanks! Will merge.

**Pull request merged**
